import { DisableDraftMode } from '@/components/DisableDraftMode'
import { ThemeProvider } from '@/components/theme-provider'
import type { Metadata } from 'next'
import { VisualEditing } from 'next-sanity'
import { Geist, Geist_Mono } from 'next/font/google'
import { draftMode } from 'next/headers'
import Script from 'next/script'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{(await draftMode()).isEnabled && (
					<>
						<DisableDraftMode />
						<VisualEditing />
					</>
				)}

				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>

				{/* EqualWeb Accessibility Script */}
				<Script id='equalweb-accessibility' strategy='afterInteractive'>
					{`
            window.interdeal = {
                "sitekey": "9dccfcc43b332a0dbc5e4865d19dca23",
                "Position": "Left",
                "domains": {
                    "js": "https://cdn.equalweb.com/",
                    "acc": "https://access.equalweb.com/"
                },
                "Menulang": "EN",
                "btnStyle": {
                    "vPosition": [
                        "80%",
                        "80%"
                    ],
                    "scale": [
                        "0.5",
                        "0.5"
                    ],
                    "color": {
                        "main": "#1c4bb6",
                        "second": "#ffffff"
                    },
                    "icon": {
                        "outline": false,
                        "type": 11,
                        "shape": "circle"
                    }
                }
            };
            (function(doc, head, body){
                var coreCall             = doc.createElement('script');
                coreCall.src             = interdeal.domains.js + 'core/5.1.2/accessibility.js';
                coreCall.defer           = true;
                coreCall.integrity       = 'sha512-PUyQFF3HFjRiVfjOiFFu+RTc0nGmLV5FN3CVw8zWFK6pVbWPAEKy9X2bTUn10GNu1EbxN56MuWu0P8ZHC6xv3Q==';
                coreCall.crossOrigin     = 'anonymous';
                coreCall.setAttribute('data-cfasync', true );
                body? body.appendChild(coreCall) : head.appendChild(coreCall);
            })(document, document.head, document.body);
          `}
				</Script>
			</body>
		</html>
	)
}
