import { SidebarProvider } from '@/components/providers/sidebar-provider'
import { ThemeProvider } from '@/components/theme-provider'
import { SanityLive } from '@/sanity/lib/live'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Educetera',
	description: 'Generated by create next app',
}

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<ThemeProvider
				attribute='class'
				defaultTheme='system'
				enableSystem
				disableTransitionOnChange
			>
				<SidebarProvider>
					<div className='h-full'>{children}</div>
				</SidebarProvider>
			</ThemeProvider>

			<SanityLive />
		</ClerkProvider>
	)
}
